'use strict';
const $=id=>document.getElementById(id), KEY='english-loop-v1';
let db, data={version:1,custom:[],logs:[]},current=null,shown=false,started=0,timer=null,seq=0,recent=[],pending=null,recognition=null,recorder=null,stream=null,audioURL=null,round=0,autoSession=false,grading=false,hintUsed=false;
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2);
const cards=()=>{const m=new Map(CARDS.map(c=>[c.id,c]));data.custom.forEach(c=>m.set(c.id,{...m.get(c.id),...c,patternIds:c.patternIds||m.get(c.id)?.patternIds||[]}));return [...m.values()];};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function normalize(s){return s.toLowerCase().replace(/[’‘]/g,"'").replace(/\bi'm\b/g,'i am').replace(/\byou're\b/g,'you are').replace(/\bit's\b/g,'it is').replace(/\bthat's\b/g,'that is').replace(/\bwhere's\b/g,'where is').replace(/\bwhat's\b/g,'what is').replace(/\bdon't\b/g,'do not').replace(/\bcan't\b/g,'cannot').replace(/\bcan not\b/g,'cannot').replace(/\bdoesn't\b/g,'does not').replace(/\bi'll\b/g,'i will').replace(/\bi'd\b/g,'i would').replace(/\bi've\b/g,'i have').replace(/[^a-z0-9\s]/g,'').replace(/\s+/g,' ').trim();}
function compare(text,c){return [c.en,...c.alt].some(a=>normalize(a)===normalize(text));}
function status(s){$('status').textContent=s;}
function save(){return new Promise((resolve,reject)=>{if(!db){status('저장할 수 없어요. 백업을 내려받고 일반 브라우저에서 다시 열어 주세요.');reject(Error('storage unavailable'));return;}const tx=db.transaction('state','readwrite');tx.objectStore('state').put(data,'main');tx.oncomplete=resolve;tx.onerror=()=>{status('저장에 실패했어요. 기록을 백업해 주세요.');reject(tx.error);};});}
function summary(id){const logs=data.logs.filter(x=>x.cardId===id),last=logs.slice(-3),days=new Set(logs.filter(x=>x.correct&&x.ms<=5000&&!x.assisted).map(x=>new Date(x.time).toLocaleDateString()));return {tries:logs.length,wrong:logs.filter(x=>!x.correct).length,last:logs.at(-1),lastTwo:logs.slice(-2),stable:last.length===3&&last.every(x=>x.correct)&&days.size>=3,days:days.size};}
const LEVELS={new:{dot:'⚪',name:'새 카드'},learning:{dot:'🟠',name:'연습 중'},familiar:{dot:'🟡',name:'익숙함'},mastered:{dot:'🟢',name:'완전히 외움'}};
function level(s){if(!s.tries)return 'new';if(s.stable)return 'mastered';const l2=s.lastTwo||[];return l2.length===2&&l2.every(x=>x.correct)?'familiar':'learning';}
function levelCounts(list,stat){const n={new:0,learning:0,familiar:0,mastered:0};list.forEach(c=>n[level(stat(c.id))]++);return n;}
function levelBar(n,total){const seg=k=>n[k]?`<i class="lv-${k}" style="flex:${n[k]}"></i>`:'';return `<span class="lvbar" role="img" aria-label="완전히 외움 ${n.mastered}, 익숙함 ${n.familiar}, 연습 중 ${n.learning}, 새 카드 ${n.new}">${seg('mastered')}${seg('familiar')}${seg('learning')}${seg('new')}</span>`;}
function levelLine(n){return ['mastered','familiar','learning','new'].filter(k=>n[k]).map(k=>`<span class="lv">${LEVELS[k].dot} ${LEVELS[k].name} <b>${n[k]}</b></span>`).join('');}
function daysLeft(s){return Math.max(0,3-(s.days||0));}
function refreshPatterns(){
 const pool=PATTERNS.filter(p=>$('deck').value==='all'||p.deck===$('deck').value);
 $('patternFilter').innerHTML='<option value="all">모든 틀</option>'+pool.map(p=>`<option value="${p.id}">${esc(p.template)}</option>`).join('');
 $('patternLabel').hidden=$('stage').value!=='pattern';
}
function eligible(){
 const stage=$('stage').value,pid=$('patternFilter').value,deck=$('deck').value;
 let a=cards();
 if(stage==='pattern'){
  const selected=PATTERNS.filter(p=>(deck==='all'||p.deck===deck)&&(pid==='all'||p.id===pid));
  const ids=new Set(selected.flatMap(p=>p.cardIds));a=a.filter(c=>ids.has(c.id));
 }else{a=a.filter(c=>deck==='all'||c.deck===deck);if(stage==='ordered'){const rank={core:0,pattern:1,extended:2};a=a.map((c,i)=>[c,i]).sort((x,y)=>(rank[x[0].stage||'core']-rank[y[0].stage||'core'])||x[1]-y[1]).map(x=>x[0]);}else if(stage!=='all')a=a.filter(c=>(c.stage||'core')===stage);}
 if($('visual').value==='image')a=a.filter(c=>c.image);
 if($('visual').value==='text')a=a.filter(c=>!c.image);
 if($('order').value==='wrong')a=a.filter(c=>summary(c.id).wrong>0&&!summary(c.id).stable);if($('order').value==='new')a=a.filter(c=>!summary(c.id).tries);
 return a;
}
function stopAudio(){window.speechSynthesis?.cancel();modelAudio?.pause();if(recognition){recognition.abort();recognition=null;}if(recorder&&recorder.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());stream=null;$('record').textContent='● 내 음성 녹음';$('recognize').disabled=false;}
function arm(){clearInterval(timer);const delay=+$('delay').value;if(!delay||!autoSession||shown||!current)return;let left=delay;$('countdown').textContent=left+'초 뒤 정답';timer=setInterval(()=>{left--;$('countdown').textContent=left+'초 뒤 정답';if(left<=0)reveal();},1000);}
function next(){round++;clearInterval(timer);stopAudio();pending=null;shown=false;hintUsed=false;$('patternHint').hidden=true;$('hintText').hidden=true;$('transcript').textContent='';$('playback').hidden=true;if(audioURL){URL.revokeObjectURL(audioURL);audioURL=null;}const a=eligible();if(!a.length){current=null;const noNew=$('order').value==='new';$('korean').textContent=noNew?'이 묶음의 새 카드를 모두 해봤어요!':'이 조건에 맞는 카드가 없어요.';$('context').textContent=noNew?'반복 방식을 순서대로 또는 오답 우선으로 바꿔 복습해 보세요.':'학습 묶음이나 반복 방식을 바꿔 주세요.';$('picture').hidden=true;$('answer').hidden=true;$('grading').hidden=true;$('reveal').hidden=true;$('countdown').textContent='';$('speechPanel').hidden=true;return;}if($('order').value==='new'){current=a.find(c=>!recent.slice(-3).includes(c.id))||a[0];}else if($('order').value==='sequence'){current=a[seq++%a.length];}else{const candidates=a.filter(c=>!recent.slice(-Math.min(3,a.length-1)).includes(c.id));const pool=candidates.length?candidates:a;const weights=pool.map(c=>{const s=summary(c.id);return !s.tries?4:!s.last.correct?8:s.stable?1:3;});let roll=Math.random()*weights.reduce((x,y)=>x+y,0),i=0;while(i<weights.length-1&&(roll-=weights[i])>0)i++;current=pool[i];}recent.push(current.id);recent=recent.slice(-6);$('pattern').textContent=(DECKS.find(d=>d.id===current.deck)?.title||'내 표현');const selectedPattern=PATTERNS.find(p=>p.id===$('patternFilter').value)||PATTERNS.find(p=>p.cardIds.includes(current.id));$('patternHint').hidden=$('stage').value!=='pattern'||!selectedPattern;$('hintText').textContent=selectedPattern?.template||'';$('position').textContent=(a.indexOf(current)+1)+' / '+a.length;$('context').textContent=current.context||'';$('korean').textContent=current.image?'이것을 일본어로?':current.ko;$('picture').hidden=!current.image;$('picture').replaceChildren();if(current.image){if(current.image.startsWith('data:image/')){const img=document.createElement('img');img.src=current.image;img.alt='이름을 말할 그림';$('picture').append(img);}else $('picture').textContent=current.image;}$('english').textContent=current.en;$('note').textContent=current.note;const sim=current.similar||[],alts=current.alt||[];$('similar').hidden=!sim.length&&!alts.length;$('similar').innerHTML=(alts.length?`<p><b>같이 정답</b> <span lang="ja">${esc(alts.join(' / '))}</span></p>`:'')+(sim.length?'<p><b>비슷한 표현</b></p><ul>'+sim.map(s=>`<li><span lang="ja">${esc(s.en)}</span> <small>${esc(s.ko)}</small></li>`).join('')+'</ul>':'');$('tip').textContent=current.tip||'모범 음성을 듣고 강세와 리듬을 따라 말해 보세요.';$('answer').hidden=true;$('grading').hidden=true;$('reveal').hidden=false;$('speechPanel').hidden=$('mode').value!=='speech';$('countdown').textContent='';status('');started=performance.now();arm();updateToday();}
let selectedVoice='',speakGeneration=0;
try{selectedVoice=localStorage.getItem('loop-voice')||'';}catch{}
function loadVoices(){
 const voices=(window.speechSynthesis?.getVoices()||[]).filter(v=>/^ja[-_]/i.test(v.lang));
 const preferred=voices.find(v=>v.voiceURI===selectedVoice)||voices.find(v=>/ja[-_]JP/i.test(v.lang)&&/natural|enhanced|premium|google/i.test(v.name))||voices.find(v=>/ja[-_]JP/i.test(v.lang))||voices[0];
 $('voice').innerHTML=voices.length?voices.map(v=>`<option value="${esc(v.voiceURI)}">${esc(v.name)} · ${esc(v.lang)}</option>`).join(''):'<option value="">사용 가능한 일본어 목소리가 없어요</option>';
 if(preferred)$('voice').value=preferred.voiceURI;
 $('voiceInfo').textContent=preferred?'현재: '+preferred.name+' · 기기 제공 음성':'일본어 목소리 설치 또는 브라우저 변경이 필요할 수 있어요.';
 return preferred;
}
let modelAudio=null;
const audioFile=c=>window.AUDIO?.files?.[c.en.trim()];
function playCard(c){const file=audioFile(c);stopAudio();if(file){modelAudio=modelAudio||new Audio();modelAudio.src=window.AUDIO_DATA?.[file]?'data:audio/mpeg;base64,'+window.AUDIO_DATA[file]:'audio/'+file;modelAudio.playbackRate=1;modelAudio.play().catch(()=>{});}else if(window.speechSynthesis){const u=new SpeechSynthesisUtterance(c.en);u.lang='ja-JP';speechSynthesis.speak(u);}}
async function speak(rate=1){
 if(!current)return;
 if(recognition||recorder?.state==='recording'){status('말하기·녹음을 끝낸 뒤 모범 음성을 들어 주세요.');return;}
 const file=audioFile(current);
 if(file){
  window.speechSynthesis?.cancel();const token=round;modelAudio=modelAudio||new Audio();
  modelAudio.src=window.AUDIO_DATA?.[file]?'data:audio/mpeg;base64,'+window.AUDIO_DATA[file]:'audio/'+file;modelAudio.playbackRate=rate;modelAudio.preservesPitch=true;modelAudio.webkitPreservesPitch=true;
  modelAudio.play().catch(e=>{if(token===round&&e.name!=='AbortError')status('음성을 재생하지 못했어요. 모범 음성 버튼을 다시 눌러 주세요.');});
  return;
 }
 if(!window.speechSynthesis){status('이 브라우저는 음성 재생을 지원하지 않아요.');return;}
 const token=round,gen=++speakGeneration;
 let voices=speechSynthesis.getVoices();
 if(!voices.length){await new Promise(resolve=>setTimeout(resolve,800));voices=speechSynthesis.getVoices();}
 if(token!==round||gen!==speakGeneration||$('practice').hidden||document.hidden)return;
 const v=voices.find(v=>v.voiceURI===$('voice').value&&/^ja[-_]/i.test(v.lang))||loadVoices();
 if(!v){status('일본어 목소리를 찾지 못했어요. 음성 설정을 확인해 주세요.');return;}
 speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.en);u.voice=v;u.lang=v.lang;u.rate=rate;
 u.onerror=e=>{if(token===round&&!['interrupted','canceled'].includes(e.error))status('음성을 재생하지 못했어요. 모범 음성 버튼을 다시 눌러 주세요.');};speechSynthesis.speak(u);
}
function reveal(){if(!current||shown)return;shown=true;clearInterval(timer);if(recognition){recognition.abort();recognition=null;}pending=pending||{ms:Math.round(performance.now()-started)};$('answer').hidden=false;$('grading').hidden=false;$('reveal').hidden=true;$('countdown').textContent='';if($('autovoice').checked)speak();}
async function grade(correct){if(!current||!shown||grading)return;const gradedId=current.id,before=level(summary(gradedId));grading=true;const log={id:uid(),cardId:current.id,time:new Date().toISOString(),correct,source:pending?.source||'self',heard:pending?.heard||'',ms:pending?.ms||0,assisted:hintUsed||!!pending?.assisted,autoCorrect:pending?.autoCorrect??null};data.logs.push(log);let failed=false;try{await save();}catch{failed=true;}grading=false;next();if(failed)status('이번 기록은 임시로만 남아 있어요. 기록·백업에서 백업해 주세요.');else{const s=summary(gradedId),after=level(s);if(after!==before&&after==='mastered')status('🟢 완전히 외웠어요!');else if(after!==before&&after==='familiar')status(`🟡 익숙해졌어요! 다른 날 ${daysLeft(s)}번 더 맞히면 완전히 외움`);else if(correct&&after==='familiar'&&daysLeft(s))status(`🟡 완전히 외움까지 다른 날 ${daysLeft(s)}번 더`);}}
function recognize(){if(!current)return;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){status('이 브라우저에서는 음성 인식을 사용할 수 없어요. 빠른 반복 모드를 사용하거나 아이폰 Safari / PC Chrome에서 열어 주세요.');return;}stopAudio();clearInterval(timer);const token=round,wasShown=shown;let got=false;recognition=new SR();const r=recognition;r.lang='ja-JP';r.interimResults=false;r.maxAlternatives=3;$('recognize').disabled=true;status('듣고 있어요. 일본어로 말해 주세요.');r.onresult=e=>{if(token!==round)return;got=true;const heard=e.results[0][0].transcript;const ok=compare(heard,current);pending={source:'speech',heard,autoCorrect:ok,ms:Math.round(performance.now()-started),assisted:wasShown};$('transcript').textContent='들은 내용: '+heard;recognition=null;$('recognize').disabled=false;reveal();status(ok?'등록된 정답과 일치해요. O를 눌러 기록하세요.':'등록된 정답과 달라요. 아래 정답과 단어를 비교하세요. 잘못 알아들었다면 O로 기록해도 됩니다.');};r.onerror=e=>{if(token!==round)return;status(({'not-allowed':'마이크 권한을 허용해 주세요. Safari에서는 Siri 설정도 확인해 주세요.','no-speech':'말소리를 듣지 못했어요. 다시 말해 주세요.','network':'음성 인식 연결에 실패했어요. 빠른 반복은 계속 사용할 수 있어요.'})[e.error]||'음성 인식을 마쳤어요. 다시 시도할 수 있어요.');};r.onend=()=>{if(token!==round)return;recognition=null;$('recognize').disabled=false;if(!got&&!shown)$('countdown').textContent='다시 말하기 또는 정답 확인을 눌러 주세요.';};try{r.start();}catch{recognition=null;$('recognize').disabled=false;status('음성 인식을 시작하지 못했어요. 다시 시도해 주세요.');}}
async function record(){if(!current)return;if(recorder?.state==='recording'){recorder.stop();stream?.getTracks().forEach(t=>t.stop());$('record').textContent='● 내 음성 녹음';return;}stopAudio();clearInterval(timer);const token=round;try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error();const s=await navigator.mediaDevices.getUserMedia({audio:true});if(token!==round){s.getTracks().forEach(t=>t.stop());return;}stream=s;const chunks=[];const r=new MediaRecorder(stream);recorder=r;r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onstop=()=>{s.getTracks().forEach(t=>t.stop());if(token!==round)return;if(audioURL)URL.revokeObjectURL(audioURL);audioURL=URL.createObjectURL(new Blob(chunks,{type:chunks[0]?.type||r.mimeType}));$('playback').src=audioURL;$('playback').hidden=false;status('내 음성을 들어 보세요. 다음 카드로 가면 녹음은 삭제돼요.');};r.start();$('record').textContent='■ 녹음 끝내기';status('녹음 중이에요. 말한 뒤 녹음 끝내기를 눌러 주세요.');}catch{status('녹음할 수 없어요. 마이크 권한과 보안 연결(HTTPS)을 확인해 주세요.');}}
function updateToday(){$('todayCount').textContent=data.logs.filter(x=>new Date(x.time).toDateString()===new Date().toDateString()).length;}
function setTab(name){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===name));clearInterval(timer);stopAudio();if(name==='library')renderLibrary();if(name==='history')renderHistory();if(name==='practice')arm();}
function renderLibrary(){$('curriculumCount').textContent=cards().length+'개 카드 · '+PATTERNS.length+'개 문장 틀 · '+DECKS.filter(d=>d.id!=='custom').length+'개 학습 묶음';$('decks').innerHTML=DECKS.map(d=>{const a=cards().filter(c=>c.deck===d.id),lv=levelCounts(a,summary);return `<article class="deck-item"><small>${a.length}문장</small>${levelBar(lv,a.length)}<span class="lvline">${levelLine(lv)}</span><h2>${esc(d.title)}</h2><p>${esc(d.description)}</p><div class="deck-actions"><button data-view="${d.id}">문장 보기</button><button data-start="${d.id}">이 묶음 연습</button>${lv.new?`<button class="newonly" data-startnew="${d.id}">⚪ 새 카드 ${lv.new}장만 연습</button>`:'<button class="newonly newonly-spacer" aria-hidden="true" tabindex="-1">⚪</button>'}</div></article>`;}).join('');if(!$('deckView').hidden)viewDeck($('deckView').dataset.deck,false);renderPhrases();}
function viewDeck(id,scroll=true){const d=DECKS.find(x=>x.id===id);if(!d)return;const a=cards().filter(c=>c.deck===id);const box=$('deckView');box.dataset.deck=id;box.hidden=false;$('deckViewTitle').textContent=d.title;$('deckViewMeta').textContent=a.length+'개 표현 · '+d.description;$('deckViewStart').dataset.start=id;$('deckViewList').innerHTML=!a.length?`<p class="deck-empty">${id==='custom'?'아직 추가한 표현이 없어요.<br>이 창을 닫고 아래 <b>내 표현 추가·수정</b>에서 한국어와 일본어를 넣어 저장하면 여기에 생겨요.':'이 묶음에는 아직 문장이 없어요.'}</p>`:a.map(c=>{const s=summary(c.id);const lv=level(s);const rec=`${LEVELS[lv].dot} `+(s.tries?`○${s.tries-s.wrong} ✕${s.wrong}`+(lv==='mastered'?'':` · 외움까지 ${daysLeft(s)}일`):'새 카드');const extra=(c.alt||[]).length?`<small>같이 정답: ${esc(c.alt.join(' / '))}</small>`:'';return `<div class="phrase"><div><p>${esc(c.image?'(그림) '+c.ko:c.ko)}</p><p lang="ja"><strong>${esc(c.en)}</strong></p>${extra}</div><div class="phrase-side"><small>${rec}</small><button data-play="${esc(c.id)}" aria-label="${esc(c.en)} 듣기">▷</button></div></div>`;}).join('');document.body.classList.add('sheet-open');$('deckViewList').scrollTop=0;}
function renderPhrases(){const q=$('search').value.toLowerCase();$('phrases').innerHTML=cards().filter(c=>(c.ko+' '+c.en).toLowerCase().includes(q)).map(c=>`<div class="phrase"><div><p>${esc(c.ko)}</p><p lang="ja">${esc(c.en)}</p></div><button data-edit="${esc(c.id)}">수정</button></div>`).join('');}
function renderHistory(){renderPatternStats();const a=cards(),stable=a.filter(c=>summary(c.id).stable).length,ok=data.logs.filter(x=>x.correct).length;$('stats').innerHTML=`<div class="stat">누적 시도<strong>${data.logs.length}</strong></div><div class="stat">O 기록<strong>${ok}</strong></div><div class="stat">완전히 외운 문장<strong>${stable} / ${a.length}</strong></div>`;$('weak').innerHTML='<p class="muted">완전히 외움 기준: 최근 3번 연속 O, 그리고 서로 다른 3일에 5초 안에 힌트 없이 O. 그래서 빨라도 3일째부터 올라가요.</p>'+a.map(c=>({c,s:summary(c.id)})).filter(x=>x.s.wrong&&!x.s.stable).sort((a,b)=>b.s.wrong-a.s.wrong).slice(0,20).map(({c,s})=>`<div class="phrase"><div>${esc(c.ko)}<p>${esc(c.en)}</p></div><small>X ${s.wrong}회 / ${s.tries}회</small></div>`).join('');$('logs').innerHTML=data.logs.slice(-100).reverse().map(x=>{const c=a.find(c=>c.id===x.cardId);return `<div class="log"><div><p>${x.correct?'○':'✕'} ${esc(c?.ko||x.cardId)}</p><small>${esc(x.heard||c?.en||'')} · ${x.source==='speech'?'음성 비교 후 확인':'직접 판정'}${x.assisted?' · 힌트·정답 참고':''}</small></div><small>${new Date(x.time).toLocaleString('ko-KR')}</small></div>`;}).join('')||'<p>첫 연습을 시작하면 기록이 여기에 쌓여요.</p>';}
function renderPatternStats(){
 $('patternStats').innerHTML=PATTERNS.map(p=>{const logs=data.logs.filter(l=>p.cardIds.includes(l.cardId));if(!logs.length)return '';const ok=logs.filter(l=>l.correct).length;return `<div class="phrase"><div>${esc(p.template)}<p class="muted">${esc(p.meaning)} · ${p.cardIds.length}개 변형</p></div><small>O ${ok} · X ${logs.length-ok}</small></div>`;}).join('')||'<p class="muted">바꿔 말하기 카드를 연습하면 같은 틀의 기록이 함께 모여요.</p>';
}
function edit(id){const c=cards().find(x=>x.id===id);$('editId').value=id||'';$('editKo').value=c?.ko||'';$('editEn').value=c?.en||'';$('editAlt').value=c?.alt.join('\n')||'';$('editNote').value=c?.context||'';$('editImage').value='';$('editForm').closest('details').open=true;$('editKo').focus();}
function editMsg(t,bad){const m=$('editStatus');m.textContent=t;m.classList.toggle('bad',!!bad);m.hidden=false;}
async function savePhrase(e){e.preventDefault();const old=cards().find(c=>c.id===$('editId').value),id=old?.id||'custom-'+uid();let image=old?.image||'';const f=$('editImage').files[0];if(f){if(!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>1024*1024){editMsg('PNG, JPG, WebP 그림을 1MB 이하로 선택해 주세요.',true);return;}image=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});}const isNew=!old;const c={...old,id,deck:old?.deck||'custom',ko:$('editKo').value.trim(),en:$('editEn').value.trim(),alt:$('editAlt').value.split('\n').map(s=>s.trim()).filter(Boolean),context:$('editNote').value.trim(),pattern:old?.pattern||'내 표현',note:'내가 등록한 표현',tip:old?.tip||'모범 음성을 듣고 따라 말해 보세요.',image,updatedAt:new Date().toISOString()};if(!c.ko||!c.en)return;data.custom=data.custom.filter(x=>x.id!==id);data.custom.push(c);try{await save();edit('');renderLibrary();editMsg(isNew?`'${c.ko}' 저장했어요. '내 표현' 묶음에서 볼 수 있어요.`:`'${c.ko}' 수정했어요. 원래 묶음(${DECKS.find(d=>d.id===c.deck)?.title||'내 표현'})에 그대로 있어요.`);}catch{editMsg('저장하지 못했어요. 다시 눌러 보고, 계속 안 되면 기록 탭에서 백업해 주세요.',true);}}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='english-loop-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('backupStatus').textContent='다운로드한 파일을 안전한 곳에 보관하세요.';}
function validBackup(x){if(!x||x.version!==1||!Array.isArray(x.custom)||!Array.isArray(x.logs)||x.logs.length>200000)return false;return x.custom.every(c=>c&&typeof c.id==='string'&&typeof c.deck==='string'&&typeof c.ko==='string'&&typeof c.en==='string'&&Array.isArray(c.alt)&&c.alt.every(a=>typeof a==='string')&&(!c.image||typeof c.image==='string'&&(!c.image.startsWith('data:')||/^data:image\/(png|jpeg|webp);base64,/.test(c.image))))&&x.logs.every(l=>l&&typeof l.id==='string'&&typeof l.cardId==='string'&&typeof l.correct==='boolean'&&Number.isFinite(Date.parse(l.time))&&Number.isFinite(l.ms)&&l.ms>=0&&['self','speech'].includes(l.source));}
async function importData(e){const file=e.target.files[0];if(!file)return;try{if(file.size>25*1024*1024)throw Error();const x=JSON.parse(await file.text());if(!validBackup(x))throw Error();const cm=new Map(data.custom.map(c=>[c.id,c]));x.custom.forEach(c=>{const old=cm.get(c.id);if(!old||(c.updatedAt||'')>(old.updatedAt||''))cm.set(c.id,c);});const lm=new Map(data.logs.map(l=>[l.id,l]));x.logs.forEach(l=>{if(!lm.has(l.id))lm.set(l.id,l);});const merged={version:1,custom:[...cm.values()],logs:[...lm.values()].sort((a,b)=>Date.parse(a.time)-Date.parse(b.time))};const previous=data;data=merged;try{await save();}catch(err){data=previous;throw err;}$('backupStatus').textContent='기록을 합쳤어요. 중복 시도는 한 번만 반영됩니다.';renderHistory();next();}catch{$('backupStatus').textContent='가져오지 못했어요. LOOP에서 내려받은 25MB 이하의 백업인지 확인해 주세요.';}e.target.value='';}
function init(){DECKS.push({id:'custom',title:'내 표현',description:'직접 추가한 문장과 그림'});$('deck').innerHTML='<option value="all">모든 묶음 섞기</option>'+DECKS.map(d=>`<option value="${d.id}">${esc(d.title)}</option>`).join('');$('deck').value='greet';document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));['deck','order','visual','mode','stage','patternFilter'].forEach(id=>$(id).onchange=()=>{seq=0;recent=[];if(['deck','stage'].includes(id))refreshPatterns();next();});refreshPatterns();$('showHint').onclick=()=>{hintUsed=true;$('hintText').hidden=false;};loadVoices();window.speechSynthesis?.addEventListener('voiceschanged',loadVoices);$('voice').onchange=()=>{selectedVoice=$('voice').value;try{localStorage.setItem('loop-voice',selectedVoice);}catch{}loadVoices();};$('delay').onchange=()=>{autoSession=true;arm();};$('reveal').onclick=reveal;$('right').onclick=()=>grade(true);$('wrong').onclick=()=>grade(false);$('skip').onclick=next;$('listen').onclick=()=>speak();$('slow').onclick=()=>speak(.75);$('recognize').onclick=recognize;$('record').onclick=record;$('search').oninput=renderPhrases;$('editForm').onsubmit=savePhrase;$('cancelEdit').onclick=()=>edit('');$('export').onclick=exportData;$('import').onchange=importData;document.addEventListener('click',e=>{const start=e.target.closest('[data-start]'),ed=e.target.closest('[data-edit]');if(start){$('deck').value=start.dataset.start;$('visual').value=start.dataset.start==='picture'?'image':'text';$('stage').value='ordered';seq=0;refreshPatterns();setTab('practice');next();}if(ed)edit(ed.dataset.edit);const vw=e.target.closest('[data-view]'),pl=e.target.closest('[data-play]');if(vw)viewDeck(vw.dataset.view);if(pl){const c=cards().find(x=>x.id===pl.dataset.play);if(c)playCard(c);}if(e.target.closest('#deckViewClose')||e.target===$('deckView')){$('deckView').hidden=true;document.body.classList.remove('sheet-open');}});document.addEventListener('keydown',e=>{
 if($('practice').hidden||/INPUT|TEXTAREA|SELECT|AUDIO|SUMMARY/.test(e.target.tagName)||e.target.isContentEditable||e.isComposing||e.keyCode===229||e.repeat||e.ctrlKey||e.metaKey||e.altKey)return;
 const code=e.code;
 if(['Space','Digit1','Numpad1','Digit2','Numpad2','KeyX','KeyO','KeyR','ArrowRight'].includes(code))e.preventDefault();
 if(code==='Space')reveal();
 else if(['Digit1','Numpad1','KeyX'].includes(code))grade(false);
 else if(['Digit2','Numpad2','KeyO'].includes(code))grade(true);
 else if(code==='KeyR'&&shown)speak();
 else if(code==='ArrowRight'&&!grading)next();
});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInterval(timer);stopAudio();}});next();if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_learning_progress',description:'Read local English practice counts without changing records.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No arguments expected');return {attempts:data.logs.length,cards:cards().length,stable:cards().filter(c=>summary(c.id).stable).length};}})).catch(()=>{});}catch{}}}
try{const req=indexedDB.open(KEY,1);req.onupgradeneeded=()=>req.result.createObjectStore('state');req.onsuccess=()=>{db=req.result;const r=db.transaction('state').objectStore('state').get('main');r.onsuccess=()=>{if(r.result&&validBackup(r.result))data=r.result;init();};r.onerror=()=>init();};req.onerror=()=>{init();status('기기 저장소를 열지 못했어요. 일반 브라우저에서 다시 열어 주세요.');};}catch{init();status('기기 저장소를 열지 못했어요.');}
